export const levels = [
  {
    id: 1,
    title: "Right to Education",
    description: "Access, teachers, and proper learning space",
    badge: "📚 Education Hero",
    sceneIds: ["education"],
  },
  {
    id: 2,
    title: "Right to Safety",
    description: "Speaking up and seeking help",
    badge: "🛡️ Safety Guardian",
    sceneIds: ["safety"],
  },
  {
    id: 3,
    title: "Right to Equality",
    description: "Fair access for everyone",
    badge: "⚖️ Equality Champion",
    sceneIds: ["equality"],
  },
  {
    id: 4,
    title: "Right to Play",
    description: "Space and opportunity to play",
    badge: "⚽ Play Master",
    sceneIds: ["play"],
  },
  {
    id: 5,
    title: "Right to Health",
    description: "Care, clean water, and nutrition",
    badge: "❤️ Health Helper",
    sceneIds: ["health"],
  },
  {
    id: 6,
    title: "Right to Be Heard",
    description: "Express thoughts and be listened to",
    badge: "🗣️ Voice Advocate",
    sceneIds: ["heard"],
  },
  {
    id: 7,
    title: "Right to Dignity",
    description: "Respect, kindness, and self-worth",
    badge: "👑 Dignity Protector",
    sceneIds: ["dignity"],
  },
  {
    id: 8,
    title: "Right to Information",
    description: "Access safe and useful information",
    badge: "📖 Info Navigator",
    sceneIds: ["information"],
  },
  {
    id: 9,
    title: "Protection from Child Labour",
    description: "Every child deserves education, not exploitation",
    badge: "✊ Labor Defender",
    sceneIds: ["childlabour"],
  },
  {
    id: 10,
    title: "Protection from Early Marriage",
    description: "Education and freedom to choose",
    badge: "💪 Future Builder",
    sceneIds: ["earlymarriage"],
  },
];
